/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StrictMath */

#ifndef _Included_StrictMath
#define _Included_StrictMath
#ifdef __cplusplus
extern "C" {
#endif
#undef StrictMath_E
#define StrictMath_E 2.718281828459045
#undef StrictMath_PI
#define StrictMath_PI 3.141592653589793
/*
 * Class:     StrictMath
 * Method:    sin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_sin
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    cos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_cos
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    tan
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_tan
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    asin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_asin
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    acos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_acos
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    atan
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_atan
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    exp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_exp
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    log
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_log
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    log10
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_log10
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_sqrt
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    cbrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_cbrt
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    IEEEremainder
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_IEEEremainder
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     StrictMath
 * Method:    ceil
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_ceil
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    floor
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_floor
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    atan2
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_atan2
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     StrictMath
 * Method:    pow
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_pow
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     StrictMath
 * Method:    sinh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_sinh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    cosh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_cosh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    tanh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_tanh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    hypot
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_hypot
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     StrictMath
 * Method:    expm1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_expm1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     StrictMath
 * Method:    log1p
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_math_StrictMath_log1p
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
