#!/bin/bash

deps="
build-essential
texinfo
gawk
libncurses5-dev
libssl-dev
libsdl1.2-dev
libxt-dev
libgtk2.0-dev
flex
"
# For building sqlite deb
# TODO: use pbuilder-satisfydepends for these
deps+="
fakeroot
cdbs
debhelper
autoconf
automake
libtool
autotools-dev
chrpath
libreadline5-dev
tcl8.4-dev
"
# For building Python's optional standard extension modules
deps+="
libsqlite3-dev
"
# For building my extension module
deps+="
python-all-dev
"
# Dependencies of naclbuild.py
# devscripts is required for dget
deps+="
python-lxml
subversion
git-core
devscripts
"

apt-get install $deps
