/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __ObjectArrayTest__
#define __ObjectArrayTest__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT jobjectArray JNICALL Java_jni_objectarray_ObjectArrayTest_initInt2DArray(JNIEnv *env, jclass cls, int size);

#ifdef __cplusplus
}
#endif

#endif /* __ObjectArrayTest__ */
