
FROM ubuntu:22.04

# Copy arabica over
COPY arabica.tar.gz /usr/build/
WORKDIR /usr/build
RUN tar -xf arabica.tar.gz && rm arabica.tar.gz

RUN apt-get update
RUN apt-get install -y libtool scons fakeroot gawk texinfo libssl-dev libgtk2.0-dev libncurses5-dev libxslt1-dev python-pip

RUN pip2 install lxml

