/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __Callbacks__
#define __Callbacks__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT void JNICALL Java_jni_exceptions_CatchThrowTest_doit(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif

#endif /* __Callbacks__ */
