/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __HelloWorld__
#define __HelloWorld__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT void JNICALL Java_simple_helloworld_HelloWorldTest_print (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif

#endif /* __HelloWorld__ */
