/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __JNIWrap__
#define __JNIWrap__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT jint JNICALL Java_file_FileAccessTest_testFileRead(JNIEnv * env, jobject obj, jstring str);

JNIEXPORT jint JNICALL Java_file_FileAccessTest_testFileWrite(JNIEnv * env, jobject obj, jstring str);

JNIEXPORT jint JNICALL Java_file_FileAccessTest_testFileReadWrite(JNIEnv * env, jobject obj, jstring str);

#ifdef __cplusplus
}
#endif

#endif /* __JNIWrap__ */
