/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __HPdfDoc__
#define __HPdfDoc__

#ifdef __cplusplus
extern "C"
{
#endif

//JNIEXPORT jint JNICALL Java_hpdf_JpegPdfTest_hello(JNIEnv *env, jobject obj);

JNIEXPORT jint JNICALL Java_hpdf_impl_HPdfDoc_HPDFNew(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfDoc_HPDFSetCompressionMode (JNIEnv *env, jobject obj, jint hpdf, jint mode);

JNIEXPORT jint JNICALL Java_hpdf_impl_HPdfDoc_HPDFGetFont (JNIEnv *env, jobject obj, jint hpdf, jstring font_name, jstring encoding_name);

JNIEXPORT jint JNICALL Java_hpdf_impl_HPdfDoc_HPDFAddPage (JNIEnv *env, jobject obj, jint hpdf);

JNIEXPORT jint JNICALL Java_hpdf_impl_HPdfDoc_HPDFSetOpenAction (JNIEnv *env, jobject obj, jint hpdf, jint handle);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfDoc_HPDFSaveToFile (JNIEnv *env, jobject obj, jint hpdf, jstring file);

#ifdef __cplusplus
}
#endif

#endif /* __HPdfDoc__ */

