/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __HPdfImage__
#define __HPdfImage__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_hpdf_impl_HPdfImage_HPDFLoadJpegImageFromFile(JNIEnv *env, jobject obj, jint hpdf, jstring filename);

JNIEXPORT jint JNICALL Java_hpdf_impl_HPdfImage_HPDFGetWidth(JNIEnv *env, jobject obj, jint img);

JNIEXPORT jint JNICALL Java_hpdf_impl_HPdfImage_HPDFGetHeight(JNIEnv *env, jobject obj, jint img);

#ifdef __cplusplus
}
#endif

#endif /* __HPdfDoc__ */

