/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __HPdfDoc__
#define __HPdfDoc__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfDestination_HPDFSetXYZ(JNIEnv *env, jobject obj, jint hdest, jfloat left, jfloat top, jfloat zoom);

#ifdef __cplusplus
}
#endif

#endif /* __HPdfDoc__ */

