/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __HPdfDoc__
#define __HPdfDoc__

#ifdef __cplusplus
extern "C"
{
#endif

//JNIEXPORT jint JNICALL Java_hpdf_JpegPdfTest_hello(JNIEnv *env, jobject obj);

JNIEXPORT jfloat JNICALL Java_hpdf_impl_HPdfPage_HPDFGetHeight(JNIEnv *env, jobject obj, jint hpage);

JNIEXPORT jfloat JNICALL Java_hpdf_impl_HPdfPage_HPDFGetWidth(JNIEnv *env, jobject obj, jint hpage);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFSetHeight(JNIEnv *env, jobject obj, jint hpage, jfloat value);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFSetWidth(JNIEnv *env, jobject obj, jint hpage, jfloat value);

JNIEXPORT jint JNICALL Java_hpdf_impl_HPdfPage_HPDFCreateDestination(JNIEnv *env, jobject obj, jint hpage);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFBeginText(JNIEnv *env, jobject obj, jint hpage);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFSetFontAndSize(JNIEnv *env, jobject obj, jint hpage, jint handle, jfloat size);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFMoveTextPos(JNIEnv *env, jobject obj, jint hpage, jfloat x, jfloat y);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFShowText(JNIEnv *env, jobject obj, jint hpage, jstring text);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFEndText(JNIEnv *env, jobject obj, jint hpage);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFDrawImage(JNIEnv *env, jobject obj, jint hpage, jint img, jint x, jint y, jint xlim, jint ylim);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFSetRGBFill(JNIEnv *env, jobject obj, jint hpage, jfloat r, jfloat g, jfloat b);

//JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_show_description(JNIEnv *env, jobject obj, jint hpage, jfloat x, jfloat y, jstring text);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFSetTextMatrix(JNIEnv *env, jobject obj, jint hpage, jfloat val1, jfloat val2, jfloat val3, jfloat val4, jfloat xpos, jfloat ypos);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFTextOut(JNIEnv *env, jobject obj, jint hpage, jfloat x, jfloat y, jstring text);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFSetCharSpace(JNIEnv *env, jobject obj, jint hpage, jfloat space);

JNIEXPORT void JNICALL Java_hpdf_impl_HPdfPage_HPDFSetWordSpace(JNIEnv *env, jobject obj, jint hpage, jfloat space);

#ifdef __cplusplus
}
#endif

#endif /* __HPdfDoc__ */

