/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __JNIWrap__
#define __JNIWrap__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT jint JNICALL Java_jni_threading_MonitorCounter_countloop(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif

#endif /* __JNIWrap__ */
