/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __FieldAccess__
#define __FieldAccess__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jboolean JNICALL Java_jni_fieldaccess_FieldAccessTest_accessFields (JNIEnv *env, jobject obj , jobject obj2);
JNIEXPORT jint JNICALL Java_jni_fieldaccess_FieldAccessTest_checkGetIntField (JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_jni_fieldaccess_FieldAccessTest_checkGetLongField (JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_jni_fieldaccess_FieldAccessTest_checkGetBooleanField (JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_jni_fieldaccess_FieldAccessTest_checkGetObjectField (JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_jni_fieldaccess_FieldAccessTest_checkSetIntField (JNIEnv *env, jobject obj, jint value);
JNIEXPORT jint JNICALL Java_jni_fieldaccess_FieldAccessTest_checkSetBooleanField (JNIEnv *env, jobject obj, jboolean value);

JNIEXPORT jint JNICALL Java_jni_fieldaccess_FieldAccessTest_checkGetByteArrayRegion (JNIEnv *env, jobject obj, jbyteArray bytearr, jint length);
JNIEXPORT jint JNICALL Java_jni_fieldaccess_FieldAccessTest_checkSetByteArrayRegion (JNIEnv *env, jobject obj, jbyteArray bytearr, jint length);

#ifdef __cplusplus
}
#endif

#endif /* __FieldAccess__ */
