/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __StaticFieldAccess__
#define __StaticFieldAccess__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT void JNICALL Java_jni_fieldaccess_StaticFieldAccessTest_accessField(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif

#endif /* __StaticFieldAccess__ */
