/* DO NOT EDIT THIS FILE ENLESS REALLY NECESSARY - it is machine generated. */

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "HelloWorld.h"
#include "librobusta.h"

void * _handle = NULL;
char * _libName = "/home/<username>/robustatrunk/test/punit/lib/sandboxed/libHelloWorld.so";
int _sid = -1;
static void * _addr_Java_simple_helloworld_HelloWorldTest_print = NULL;
static char * _symname_Java_simple_helloworld_HelloWorldTest_print = "Java_simple_helloworld_HelloWorldTest_print";

extern LIST * gl_natp_list;

JNIEXPORT void JNICALL Java_simple_helloworld_HelloWorldTest_print (JNIEnv *env, jobject obj) {
	if (_handle == NULL) {
		ptsb retv = loadLib(env, _libName);
		_handle = retv.pointer;
		_sid = retv.sb;
	}
	if (_addr_Java_simple_helloworld_HelloWorldTest_print == NULL && _handle != NULL)
		_addr_Java_simple_helloworld_HelloWorldTest_print = (void *) loadSym(_handle, _symname_Java_simple_helloworld_HelloWorldTest_print, _sid);
	assert(_addr_Java_simple_helloworld_HelloWorldTest_print != NULL);
	assert(gl_natp_list != NULL);

	npitem * s = (npitem *) ListFirst(gl_natp_list);
	assert(s != NULL);
	NATP_PTR stub_natp = NULL;
	do {
		if (s->env == env) {
			stub_natp = s->natp[_sid];
			break;
		}
	} while((s = (npitem *) ListNext(gl_natp_list)) != NULL);

	if (stub_natp == NULL) {
		stub_natp = _Z17robusta_init_natpv();
		s = (npitem *) malloc(sizeof(npitem));
		if (s == NULL || stub_natp == NULL) {
			printf("STOP! Fail to allocate new npitem or natp!\n");
			while (1) ;
		}
		s->env = env;
		int i;
		for (i = 0; i < NUM_SANDBOX; i++) {
			if (i != _sid) s->natp[i] = _Z17robusta_init_natpv();
			else s->natp[i] = stub_natp;
		}
		ListAppend(gl_natp_list, s);
	}
	_Z7call_inPv(stub_natp, _sid, 1, 33026, _addr_Java_simple_helloworld_HelloWorldTest_print, env, obj);
}

