/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __Callbacks__
#define __Callbacks__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT jint JNICALL Java_jni_callbacks_CallbacksTest_nativeMethod(JNIEnv *env, jobject obj, jint depth);

#ifdef __cplusplus
}
#endif

#endif /* __Callbacks__ */
