/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __MultHelloWorld1__
#define __MultHelloWorld1__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT void JNICALL Java_simple_multhelloworld_MultHelloWorldTest_print1 (JNIEnv *env, jobject obj);


#ifdef __cplusplus
}
#endif

#endif /* __MultHelloWorld1__ */
