/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __MultHelloWorld2__
#define __MultHelloWorld2__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT void JNICALL Java_simple_multhelloworld_MultHelloWorldTest_print2 (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif

#endif /* __MultHelloWorld2__ */
