/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __ParamPass__
#define __ParamPass__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_simple_parampass_ParamPassTest_pass1 (JNIEnv *env, jobject obj, jint a);

JNIEXPORT jint JNICALL Java_simple_parampass_ParamPassTest_pass2 (JNIEnv *env, jobject obj, jint a, jint b);

JNIEXPORT jint JNICALL Java_simple_parampass_ParamPassTest_pass3 (JNIEnv *env, jobject obj, jint a, jint b, jint c);

JNIEXPORT jdouble JNICALL Java_simple_parampass_ParamPassTest_passprims(JNIEnv *env, jobject obj, jbyte a, jchar b, jdouble c, jfloat d, jint e, jlong f);

JNIEXPORT jstring JNICALL Java_simple_parampass_ParamPassTest_passobjtypes (JNIEnv *env, jobject obj, jclass cls, jstring str);

JNIEXPORT jint JNICALL Java_simple_parampass_ParamPassTest_passstatic (JNIEnv *env, jclass cls, jint a);

JNIEXPORT jboolean JNICALL Java_simple_parampass_ParamPassTest_returnboolean (JNIEnv * env, jobject obj);

JNIEXPORT jbyte JNICALL Java_simple_parampass_ParamPassTest_returnbyte (JNIEnv * env, jobject obj);

JNIEXPORT jchar JNICALL Java_simple_parampass_ParamPassTest_returnchar (JNIEnv * env, jobject obj);

JNIEXPORT jshort JNICALL Java_simple_parampass_ParamPassTest_returnshort (JNIEnv * env, jobject obj);

JNIEXPORT jint JNICALL Java_simple_parampass_ParamPassTest_returnint (JNIEnv * env, jobject obj);

JNIEXPORT jlong JNICALL Java_simple_parampass_ParamPassTest_returnlong (JNIEnv * env, jobject obj);

JNIEXPORT jfloat JNICALL Java_simple_parampass_ParamPassTest_returnfloat (JNIEnv *env, jobject obj);

JNIEXPORT jdouble JNICALL Java_simple_parampass_ParamPassTest_returndouble (JNIEnv *env, jobject obj);

JNIEXPORT jobject JNICALL Java_simple_parampass_ParamPassTest_returnjobject (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif

#endif /* __ParamPass__ */
