/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __JNIWrap__
#define __JNIWrap__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT jint JNICALL Java_jni_jniwrap_JNIWrapTest_testGetVersion(JNIEnv *env, jobject obj);

JNIEXPORT jint JNICALL Java_jni_jniwrap_JNIWrapTest_testJNIChecks(JNIEnv * env, jobject obj, jstring test, jintArray test2, jbyteArray test3, jcharArray test4, jlongArray test5, jobject temp);

#ifdef __cplusplus
}
#endif

#endif /* __JNIWrap__ */
