/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __IntArray__
#define __IntArray__

#ifdef __cplusplus
extern "C"
{
#endif

//
JNIEXPORT jint JNICALL Java_jni_intarray_IntArrayTest_sumArray(JNIEnv *env, jobject obj, jintArray arr);

#ifdef __cplusplus
}
#endif

#endif /* __IntArray__ */
