/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __JpegCompressTest__
#define __JpegCompressTest__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_jpeg_JpegCompressTest_compress(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif

#endif /* __HPdfDoc__ */

