/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simple_blank_BlankTest */

#ifndef _Included_simple_blank_BlankTest
#define _Included_simple_blank_BlankTest
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     simple_blank_BlankTest
 * Method:    blank
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_simple_blank_BlankTest_blank
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
